find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

zephyr_get(PRESET_NAME MERGE SYSBUILD GLOBAL)
zephyr_get(PRESET_CMAKE_FILE MERGE SYSBUILD GLOBAL)

if(DEFINED PRESET_CMAKE_FILE AND NOT "${PRESET_CMAKE_FILE}" STREQUAL "")
    include(${PRESET_CMAKE_FILE})
endif()
