find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

zephyr_get(ZENV_PRESET_CMAKE_FILE MERGE SYSBUILD GLOBAL)

if(DEFINED ZENV_PRESET_CMAKE_FILE AND NOT "${ZENV_PRESET_CMAKE_FILE}" STREQUAL "")
    include(${ZENV_PRESET_CMAKE_FILE})
endif()
