name: Docker

on:
  push:

jobs:
  x86-64:
    name: Build Docker Container / x86-64
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-x86-64
  arm64:
    name: Build Docker Container / arm64
    runs-on: self-hosted
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/arm64
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-arm64
  create-manifests:
    name: Create Docker manifests
    runs-on: ubuntu-latest
    needs: [x86-64, arm64]
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: SHA manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }} \
          ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-x86-64 \
          ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-arm64
      - name: latest manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/zenv:latest \
          ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-x86-64 \
          ghcr.io/${{ github.repository_owner }}/zenv:${{ github.sha }}-arm64
